DO $$
BEGIN
    IF to_regclass('public.reviews') IS NOT NULL THEN
        ALTER TABLE reviews ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
        ALTER TABLE reviews ADD COLUMN IF NOT EXISTS timezone_id VARCHAR(64);
        ALTER TABLE reviews ADD COLUMN IF NOT EXISTS question_format VARCHAR(32);
        ALTER TABLE reviews ADD COLUMN IF NOT EXISTS interval_before_days INTEGER;
        ALTER TABLE reviews ADD COLUMN IF NOT EXISTS interval_after_days INTEGER;
        CREATE INDEX IF NOT EXISTS idx_reviews_user_reviewed_at ON reviews (user_id, reviewed_at);
    END IF;
    IF to_regclass('public.words') IS NOT NULL THEN
        ALTER TABLE words ADD COLUMN IF NOT EXISTS difficulty_tier VARCHAR(20);
        ALTER TABLE words ADD COLUMN IF NOT EXISTS lapse_count INTEGER NOT NULL DEFAULT 0;
        CREATE INDEX IF NOT EXISTS idx_words_user_difficulty ON words (user_id, difficulty_tier);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS progress_weekly_narratives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    week_start DATE NOT NULL,
    timezone_id VARCHAR(64) NOT NULL,
    narrative TEXT NOT NULL,
    facts_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_progress_weekly_narrative UNIQUE (user_id, week_start, timezone_id)
);
CREATE INDEX IF NOT EXISTS idx_progress_narrative_user_week ON progress_weekly_narratives (user_id, week_start);