ALTER TABLE words ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE words ADD COLUMN IF NOT EXISTS deleted_by BIGINT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS pronunciation VARCHAR(255);
ALTER TABLE words ADD COLUMN IF NOT EXISTS part_of_speech VARCHAR(80);
ALTER TABLE words ADD COLUMN IF NOT EXISTS etymology TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS mnemonic TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS usage_note TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS synonyms TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS antonyms TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS source_context TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS user_example TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS user_mnemonic TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS ai_enrichment_status VARCHAR(32);
ALTER TABLE words ADD COLUMN IF NOT EXISTS ai_enrichment_version VARCHAR(32);

CREATE INDEX IF NOT EXISTS idx_words_user_deleted_at ON words (user_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_words_user_created_at ON words (user_id, created_at);