ALTER TABLE builder_installments ADD COLUMN IF NOT EXISTS payee_type VARCHAR(32);
ALTER TABLE builder_installments ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(120);
ALTER TABLE builder_installments ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(32);
ALTER TABLE property_loans ADD COLUMN IF NOT EXISTS emi_due_day INTEGER;
ALTER TABLE property_loans ADD COLUMN IF NOT EXISTS bank_confirmed_rate DECIMAL(12,6);
ALTER TABLE property_loans ADD COLUMN IF NOT EXISTS bank_confirmed_rate_date DATE;
ALTER TABLE property_loans ADD COLUMN IF NOT EXISTS bank_confirmed_emi_start_date DATE;
ALTER TABLE property_loans ADD COLUMN IF NOT EXISTS bank_confirmed_outstanding DECIMAL(19,2);
ALTER TABLE property_loans ADD COLUMN IF NOT EXISTS bank_checkpoint_date DATE;
CREATE TABLE IF NOT EXISTS property_loan_rate_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL,
    effective_date DATE NOT NULL,
    annual_rate DECIMAL(12,6) NOT NULL,
    source VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_property_rate_history_loan_date ON property_loan_rate_history (loan_id, effective_date);
